begin;

alter table public.admin_users enable row level security;
alter table public.care_requests enable row level security;
alter table public.caregiver_applications enable row level security;
alter table public.caregiver_posts enable row level security;
alter table public.caregiver_profiles enable row level security;
alter table public.caregiver_requests enable row level security;
alter table public.caregiver_reviews enable row level security;
alter table public.family_profiles enable row level security;
alter table public.family_reviews enable row level security;
alter table public.job_applications enable row level security;
alter table public.job_post_versions enable row level security;
alter table public.job_posts enable row level security;

drop policy if exists "Users can read their own admin record" on public.admin_users;
drop policy if exists "Anon can select care requests" on public.care_requests;
drop policy if exists "Authenticated can select care requests" on public.care_requests;
drop policy if exists "Public can insert care requests" on public.care_requests;
drop policy if exists admin_select_care_requests on public.care_requests;
drop policy if exists care_requests_insert_anon on public.care_requests;
drop policy if exists care_requests_insert_auth on public.care_requests;
drop policy if exists public_insert_care_requests on public.care_requests;
drop policy if exists "Public can insert caregiver applications" on public.caregiver_applications;
drop policy if exists admin_select_caregiver_applications on public.caregiver_applications;
drop policy if exists caregiver_applications_insert_auth on public.caregiver_applications;
drop policy if exists public_insert_caregiver_applications on public.caregiver_applications;
drop policy if exists admin_select_caregiver_posts on public.caregiver_posts;
drop policy if exists admin_update_caregiver_posts on public.caregiver_posts;
drop policy if exists public_select_caregivers on public.caregiver_posts;
drop policy if exists admin_select_caregiver_profiles on public.caregiver_profiles;
drop policy if exists admin_update_caregiver_profiles on public.caregiver_profiles;
drop policy if exists caregiver_insert_own_profile on public.caregiver_profiles;
drop policy if exists caregiver_select_own_profile on public.caregiver_profiles;
drop policy if exists caregiver_update_own_profile on public.caregiver_profiles;
drop policy if exists public_select_active_caregiver_profiles on public.caregiver_profiles;
drop policy if exists admin_select_caregiver_requests on public.caregiver_requests;
drop policy if exists public_insert_caregiver_requests on public.caregiver_requests;
drop policy if exists public_select_caregiver_reviews on public.caregiver_reviews;
drop policy if exists admin_select_family_profiles on public.family_profiles;
drop policy if exists admin_update_family_profiles on public.family_profiles;
drop policy if exists family_insert_own_profile on public.family_profiles;
drop policy if exists family_select_own_profile on public.family_profiles;
drop policy if exists family_update_own_profile on public.family_profiles;
drop policy if exists public_insert_family_profiles on public.family_profiles;
drop policy if exists public_select_active_family_profiles on public.family_profiles;
drop policy if exists public_select_family_profiles on public.family_profiles;
drop policy if exists public_select_family_reviews on public.family_reviews;
drop policy if exists admin_select_job_applications on public.job_applications;
drop policy if exists public_insert_job_applications on public.job_applications;
drop policy if exists "Users can view versions of their own job posts" on public.job_post_versions;
drop policy if exists "Users can view their own job posts" on public.job_posts;
drop policy if exists admin_select_job_posts on public.job_posts;
drop policy if exists admin_update_job_posts on public.job_posts;
drop policy if exists public_select_jobs on public.job_posts;

create policy "Users can read their own admin record" on public.admin_users as permissive for select to authenticated using ((auth.uid() = user_id));
create policy "Anon can select care requests" on public.care_requests as permissive for select to anon using (true);
create policy "Authenticated can select care requests" on public.care_requests as permissive for select to authenticated using (true);
create policy "Public can insert care requests" on public.care_requests as permissive for insert to anon, authenticated with check (true);
create policy admin_select_care_requests on public.care_requests as permissive for select to authenticated using (((auth.jwt() ->> 'email'::text) = 'jfrancomb@gmail.com'::text));
create policy care_requests_insert_anon on public.care_requests as permissive for insert to anon with check (true);
create policy care_requests_insert_auth on public.care_requests as permissive for insert to authenticated with check (true);
create policy public_insert_care_requests on public.care_requests as permissive for insert to anon with check (true);
create policy "Public can insert caregiver applications" on public.caregiver_applications as permissive for insert to anon, authenticated with check (true);
create policy admin_select_caregiver_applications on public.caregiver_applications as permissive for select to authenticated using (((auth.jwt() ->> 'email'::text) = 'jfrancomb@gmail.com'::text));
create policy caregiver_applications_insert_auth on public.caregiver_applications as permissive for insert to authenticated with check (true);
create policy public_insert_caregiver_applications on public.caregiver_applications as permissive for insert to anon with check (true);
create policy admin_select_caregiver_posts on public.caregiver_posts as permissive for select to authenticated using (((auth.jwt() ->> 'email'::text) = 'jfrancomb@gmail.com'::text));
create policy admin_update_caregiver_posts on public.caregiver_posts as permissive for update to authenticated using (((auth.jwt() ->> 'email'::text) = 'jfrancomb@gmail.com'::text)) with check (((auth.jwt() ->> 'email'::text) = 'jfrancomb@gmail.com'::text));
create policy public_select_caregivers on public.caregiver_posts as permissive for select to anon using ((is_active = true));
create policy admin_select_caregiver_profiles on public.caregiver_profiles as permissive for select to authenticated using (((auth.jwt() ->> 'email'::text) = 'jfrancomb@gmail.com'::text));
create policy admin_update_caregiver_profiles on public.caregiver_profiles as permissive for update to authenticated using (((auth.jwt() ->> 'email'::text) = 'jfrancomb@gmail.com'::text)) with check (((auth.jwt() ->> 'email'::text) = 'jfrancomb@gmail.com'::text));
create policy caregiver_insert_own_profile on public.caregiver_profiles as permissive for insert to authenticated with check ((auth.uid() = user_id));
create policy caregiver_select_own_profile on public.caregiver_profiles as permissive for select to authenticated using ((auth.uid() = user_id));
create policy caregiver_update_own_profile on public.caregiver_profiles as permissive for update to authenticated using ((auth.uid() = user_id)) with check ((auth.uid() = user_id));
create policy public_select_active_caregiver_profiles on public.caregiver_profiles as permissive for select to anon, authenticated using ((is_active = true));
create policy admin_select_caregiver_requests on public.caregiver_requests as permissive for select to authenticated using (((auth.jwt() ->> 'email'::text) = 'jfrancomb@gmail.com'::text));
create policy public_insert_caregiver_requests on public.caregiver_requests as permissive for insert to anon with check (true);
create policy public_select_caregiver_reviews on public.caregiver_reviews as permissive for select to anon, authenticated using ((is_visible = true));
create policy admin_select_family_profiles on public.family_profiles as permissive for select to authenticated using (((auth.jwt() ->> 'email'::text) = 'jfrancomb@gmail.com'::text));
create policy admin_update_family_profiles on public.family_profiles as permissive for update to authenticated using (((auth.jwt() ->> 'email'::text) = 'jfrancomb@gmail.com'::text)) with check (((auth.jwt() ->> 'email'::text) = 'jfrancomb@gmail.com'::text));
create policy family_insert_own_profile on public.family_profiles as permissive for insert to authenticated with check ((auth.uid() = user_id));
create policy family_select_own_profile on public.family_profiles as permissive for select to authenticated using ((auth.uid() = user_id));
create policy family_update_own_profile on public.family_profiles as permissive for update to authenticated using ((auth.uid() = user_id)) with check ((auth.uid() = user_id));
create policy public_insert_family_profiles on public.family_profiles as permissive for insert to anon, authenticated with check (true);
create policy public_select_active_family_profiles on public.family_profiles as permissive for select to anon, authenticated using ((is_active = true));
create policy public_select_family_profiles on public.family_profiles as permissive for select to anon, authenticated using ((is_active = true));
create policy public_select_family_reviews on public.family_reviews as permissive for select to anon, authenticated using ((is_visible = true));
create policy admin_select_job_applications on public.job_applications as permissive for select to authenticated using (((auth.jwt() ->> 'email'::text) = 'jfrancomb@gmail.com'::text));
create policy public_insert_job_applications on public.job_applications as permissive for insert to anon with check (true);
create policy "Users can view versions of their own job posts" on public.job_post_versions as permissive for select to authenticated using ((EXISTS ( SELECT 1
   FROM job_posts jp
  WHERE ((jp.id = job_post_versions.job_post_id) AND (jp.user_id = auth.uid())))));
create policy "Users can view their own job posts" on public.job_posts as permissive for select to authenticated using ((user_id = auth.uid()));
create policy admin_select_job_posts on public.job_posts as permissive for select to authenticated using (((auth.jwt() ->> 'email'::text) = 'jfrancomb@gmail.com'::text));
create policy admin_update_job_posts on public.job_posts as permissive for update to authenticated using (((auth.jwt() ->> 'email'::text) = 'jfrancomb@gmail.com'::text)) with check (((auth.jwt() ->> 'email'::text) = 'jfrancomb@gmail.com'::text));
create policy public_select_jobs on public.job_posts as permissive for select to anon using ((is_active = true));

commit;
